server:
  port: 0 # Puerto aleatorio para escalar

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    # IMPORTANTE: Usamos una base de datos nueva para seguridad
    url: jdbc:postgresql://localhost:5432/toolrent_auth_db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Creará las tablas de usuarios y roles automáticamente
    show-sql: true

# Configuración personalizada para JWT
jwt:
  # Esta clave larga y compleja 
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000 # 1 hora en milisegundos (60 * 60 * 1000)
